apiVersion: amtd.r6security.com/v1beta1
kind: AdaptiveMovingTargetDefense
metadata:
  labels:
    app.kubernetes.io/name: adaptivemovingtargetdefense
    app.kubernetes.io/instance: adaptivemovingtargetdefense-sample
  name: amtd-demo
spec:
  podSelector:
    app: demo-page
  strategy:
    - rule: 
        type: default
      action:
        disable: {}
    - rule: 
        type: block-pkg-mgmt-tools-exec
        threatLevel: "1"
        source: KubeArmorIntegrator
      action:
        delete: {}